create table addresses (is_default_address bit, address_id bigint not null auto_increment, createdAt datetime(6), member_id bigint, updatedAt datetime(6), post_code varchar(100) not null, address varchar(255), address_name varchar(255), detail_address varchar(255), recipient varchar(255), recipient_phone varchar(255), primary key (address_id)) engine=InnoDB;
create table cart (price decimal(38,2) not null, Product_Mgt_id bigint not null, cart_id bigint not null auto_increment, member_id bigint not null, quantity bigint not null check (quantity>=0), primary key (cart_id)) engine=InnoDB;
create table category (category_id bigint not null, depth bigint not null, parent bigint, name varchar(255) not null, primary key (category_id)) engine=InnoDB;
create table category_sequence (next_val bigint) engine=InnoDB;
insert into category_sequence values ( 1 );
create table CERTIFICATION (userId bigint not null, certificationNumber varchar(255), email varchar(255), primary key (userId)) engine=InnoDB;
create table content_imgs (content_img_id bigint not null auto_increment, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null, product_id bigint not null, image_path varchar(255) not null, primary key (content_img_id)) engine=InnoDB;
create table inquiry_reply (created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null, inquiry_id bigint not null, reply_by bigint not null, reply_id bigint not null, reply_content varchar(255) not null, reply_title varchar(255) not null, primary key (reply_id)) engine=InnoDB;
create table inquiry_reply_sequence (next_val bigint) engine=InnoDB;
insert into inquiry_reply_sequence values ( 1 );
create table inquiry_table (is_response bit, is_secret bit, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null, inquiry_id bigint not null auto_increment, member_id bigint, product_id bigint not null, inquiry_content varchar(255) not null, inquiry_title varchar(255) not null, password varchar(255) not null, writer_email varchar(255) not null, writer_name varchar(255) not null, inquiry_type enum ('PRODUCT','DELIVERY','RETURN','EXCHANGE','REFUND','ETC','NOTSELECTED') not null, primary key (inquiry_id)) engine=InnoDB;
create table member (is_accountExpired bit, is_active bit, is_admin bit, is_banned bit, is_certified_email bit, is_passwordExpired bit, joined_at datetime(6), member_id bigint not null auto_increment, email varchar(255), email_token varchar(255), nickname varchar(255), password varchar(255), phone varchar(255), social_id varchar(255), username varchar(255), member_role enum ('USER','ADMIN','SELLER','ETC'), social_type enum ('KAKAO','NAVER','GOOGLE','GENERAL','ETC'), primary key (member_id)) engine=InnoDB;
create table member_profile (createdAt datetime(6), member_id bigint, profile_id bigint not null auto_increment, updatedAt datetime(6), profileImgName varchar(255), profileImgPath varchar(255), introduction tinytext, member_ages enum ('AGE_0_TO_10','TEENS','TWENTIES','THIRTIES','FORTIES_AND_ABOVE'), member_gender enum ('MAN','WOMAN','ETC'), primary key (profile_id)) engine=InnoDB;
create table OrderProduct (priceAtOrder decimal(38,2), returned bit not null, reviewed bit not null, id bigint not null auto_increment, orders_id bigint, product_management_id bigint, quantity bigint, productName varchar(255), primary key (id)) engine=InnoDB;
create table orders (total_price decimal(38,2) not null, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null, member_id bigint not null, order_id bigint not null auto_increment, merchant_uid varchar(100), post_code varchar(100) not null, address varchar(255) not null, detail_address varchar(255), order_name varchar(255) not null, phone_number varchar(255), product_name varchar(255) not null, payMethod enum ('card','trans','vbank','phone'), payment_status enum ('PENDING','COMPLETE','CANCELED') not null, primary key (order_id)) engine=InnoDB;
create table orders_product_management (orders_id bigint not null, product_management_id bigint not null) engine=InnoDB;
create table payment_history (product_price decimal(38,2) not null, review bit, total_price decimal(38,2) not null, member bigint not null, orders bigint not null, paid_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null, payment_history_id bigint not null auto_increment, product bigint not null, quantity bigint, bankCode varchar(255), bankName varchar(255), buyerAddr varchar(255), buyerEmail varchar(255), impUid varchar(255), pay_method varchar(255), product_name varchar(255), product_option varchar(255), payment_status enum ('PENDING','COMPLETE','CANCELED') not null, status enum ('PENDING','COMPLETE','CANCELED'), primary key (payment_history_id)) engine=InnoDB;
create table payment_refund (amount integer, checksum integer, payment_history bigint, payment_refund_id bigint not null auto_increment, refund_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null, imp_uid varchar(255), reason varchar(255), refund_account varchar(255), refund_bank varchar(255), refund_holder varchar(255), refund_tel varchar(255), primary key (payment_refund_id)) engine=InnoDB;
create table product_color (color_id bigint not null auto_increment, color varchar(255), primary key (color_id)) engine=InnoDB;
create table product_management (isRestockAvailable bit not null, isRestocked bit not null, isSoldOut bit not null, additional_stock bigint, category_id bigint not null, color_id bigint not null, initial_stock bigint, inventory_id bigint not null auto_increment, product_id bigint not null, product_stock bigint, size enum ('XSMALL','SMALL','MEDIUM','LARGE','XLARGE','FREE') not null, primary key (inventory_id)) engine=InnoDB;
create table product_thumbnails (created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null, product_id bigint not null, thumbnail_id bigint not null auto_increment, image_path varchar(255) not null, primary key (thumbnail_id)) engine=InnoDB;
create table products_table (discount_rate integer, is_discount bit not null, is_recommend bit not null, price INT CHECK (price >= 0) not null, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null, product_id bigint not null auto_increment, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP not null, wishlist_count bigint, manufacturer varchar(255) not null, product_info varchar(255), product_name varchar(255) not null, product_type enum ('MAN','WOMAN','UNISEX') not null, primary key (product_id)) engine=InnoDB;
create table refresh (expiration TIMESTAMP null, member_id bigint, refresh_id bigint not null auto_increment, refresh_token varchar(255), primary key (refresh_id)) engine=InnoDB;
create table review (rating integer not null check ((rating<=5) and (rating>=1)), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null, payment_history_id bigint, review_id bigint not null auto_increment, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP not null, content varchar(255) not null, primary key (review_id)) engine=InnoDB;
create table review_image (review_id bigint not null, review_img_id bigint not null auto_increment, review_image_path varchar(255), primary key (review_img_id)) engine=InnoDB;
create table review_reply (created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null, reply_by bigint not null, reply_id bigint not null, review_id bigint not null, reply_content varchar(255) not null, primary key (reply_id)) engine=InnoDB;
create table review_reply_sequence (next_val bigint) engine=InnoDB;
insert into review_reply_sequence values ( 1 );
create table wish_list (member_id bigint not null, product_id bigint not null, wishlist_id bigint not null auto_increment, primary key (wishlist_id)) engine=InnoDB;
alter table category add constraint UK_46ccwnsi9409t36lurvtyljak unique (name);
alter table member add constraint UKghllwqgkdbwwp28ijrqih43nt unique (social_id);
alter table member_profile add constraint UK_c87j55l2co10d3t5m5xmbutu1 unique (member_id);
alter table payment_refund add constraint UK_pawk71jbyhx2pio4ag9t8qt9f unique (payment_history);
alter table product_color add constraint UK_gwdixpxwichue6v7a8gicgf45 unique (color);
alter table refresh add constraint UK_cayf9x6n7qk7ay3vbktyo7g5w unique (member_id);
alter table review add constraint UK_hnokydvmavksxheemc5em9p9u unique (payment_history_id);
alter table addresses add constraint FK2syf39vjeyb88xddln3855wmt foreign key (member_id) references member (member_id);
alter table cart add constraint FKix170nytunweovf2v9137mx2o foreign key (member_id) references member (member_id);
alter table cart add constraint FK1xq8fipq3ud87y55hx81rqwtl foreign key (Product_Mgt_id) references product_management (inventory_id);
alter table category add constraint FKcmtwvovxcdalvlgifxh6luun8 foreign key (parent) references category (category_id);
alter table content_imgs add constraint FK1v919j1qs8b7fq7icgp0dex0j foreign key (product_id) references products_table (product_id);
alter table inquiry_reply add constraint FKmxbeegd9c660870xxr909s456 foreign key (inquiry_id) references inquiry_table (inquiry_id);
alter table inquiry_reply add constraint FK2qjp7o025cut7b4hmc1nh9oyp foreign key (reply_by) references member (member_id);
alter table inquiry_table add constraint FK5st1emjtqevu8ek3ntmk32efy foreign key (member_id) references member (member_id);
alter table inquiry_table add constraint FKajsrfmq8iuo31bwf6cix8rgxd foreign key (product_id) references products_table (product_id);
alter table member_profile add constraint FKkrtcs7wdtv954e99w88uga9mq foreign key (member_id) references member (member_id);
alter table OrderProduct add constraint FKpsa4b3qqqwm2qrqmf9llljbp7 foreign key (orders_id) references orders (order_id);
alter table OrderProduct add constraint FKn5t90sott1sogojkkq2bn8y4s foreign key (product_management_id) references product_management (inventory_id);
alter table orders add constraint FKpktxwhj3x9m4gth5ff6bkqgeb foreign key (member_id) references member (member_id);
alter table orders_product_management add constraint FKacoo01kalffd1bw2kv1l76odb foreign key (product_management_id) references product_management (inventory_id);
alter table orders_product_management add constraint FKmf2lry98hla04u4ndxtlqtj06 foreign key (orders_id) references orders (order_id);
alter table payment_history add constraint FK3a3gc6gyw6v6qgj9o7x7delh foreign key (member) references member (member_id);
alter table payment_history add constraint FK216m45g4xen1hts2we5b32tfn foreign key (orders) references orders (order_id);
alter table payment_history add constraint FKk4rnqxshq1s16ctqckl95tpig foreign key (product) references products_table (product_id);
alter table payment_refund add constraint FKev5c5v2hddwnkjbjkni4fsydf foreign key (payment_history) references payment_history (payment_history_id);
alter table product_management add constraint FKb1ftxe8ayoswx3ga2kkq2c7xl foreign key (category_id) references category (category_id);
alter table product_management add constraint FKd614aaiiadbyw7uyao3hkmjeu foreign key (color_id) references product_color (color_id);
alter table product_management add constraint FK4iwwwnwf1pb6pio0xvaso8iyn foreign key (product_id) references products_table (product_id);
alter table product_thumbnails add constraint FKd9ei5b3np12uh523h9s9m8ue9 foreign key (product_id) references products_table (product_id);
alter table refresh add constraint FKp9hjvmp9hfvn3fo8fn6komqkk foreign key (member_id) references member (member_id);
alter table review add constraint FK84bxf1h3j8i4uyugd0lylf56g foreign key (payment_history_id) references payment_history (payment_history_id);
alter table review_image add constraint FK16wp089tx9nm0obc217gvdd6l foreign key (review_id) references review (review_id);
alter table review_reply add constraint FK4k0m2gusluu0fvj7c4m5i48k2 foreign key (reply_by) references member (member_id);
alter table review_reply add constraint FK3mfomicwiqwm49ahq8yevep7x foreign key (review_id) references review (review_id);
alter table wish_list add constraint FK8rt1tquybk69qkn942joirym1 foreign key (member_id) references member (member_id);
alter table wish_list add constraint FKc0hqo9qmunw8mgtm1npb0ifrb foreign key (product_id) references products_table (product_id);
